# Generated by Django 4.1.1 on 2022-11-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_alter_contact_phone_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='adress',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=None, max_length=90),
            preserve_default=False,
        ),
    ]
